# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_remove_case_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='path',
        ),
        migrations.AddField(
            model_name='case',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
